remote_theme: marella/jekyll-theme-documentation

permalink: pretty
baseurl: "/hpc-starter"
title: "HPC Starter"
description: "Get to know high performance computing, one command at a time"

nav:
- Start Here: ./
- Meet the Machine: ./system-tour
- Look Around: ./02-look-around
- 1. Make a Folder: ./03-make-a-folder
- 2. Clone a Setup: ./01-clone
- 3. Edit a Script (nano): ./04-edit-with-nano
- 4. Run Your Script: ./05-run-it
- 5. Copy a Dataset: ./06-copy-data
- Explore More (Optional): ./explore-more
- More Than One Way In: ./07-many-ways-in
- You Did It: ./08-you-did-it
